### PR TITLE
feat(download): add `FileCaption` to download template

### LINKED ISSUE #441: Add file caption in template format
Sometimes we need to download media files and kept their name as their caption.

### LINKED ISSUE #460: [Feat] download with naming
Please describe your feature request
Whether to consider the json exported with the parameter --with-content. Add the named variable (filetext) to the name, for example: --template "{{ . FileText }}"

### PR DESCRIPTION
**Pull request by XMLHexagram**
close #441
close #460

### CODE REVIEW

**Comment by mohitjoshi155** [comment]
please release this in binary file asap

**Comment by iyear** [comment]
@mohitjoshi155 v0.17.0 released

**Comment by sky32** [comment]
error:
    file name too long
fix:
```
	fileCaption := formatMessage(message.Message)

	err = i.tpl.Execute(&toName, &fileTemplate{
		DialogID:     from.ID(),
		MessageID:    message.ID,
		MessageDate:  int64(message.Date),
		FileName:     item.Name,
		FileCaption:  fileCaption,
		FileSize:     utils.Byte.FormatBinaryBytes(item.Size),
		DownloadDate: time.Now().Unix(),
	})
```
```
func formatMessage(name string) string {
	replaceName := strings.Map(func(r rune) rune {
		switch r {
		case ' ', '\\', '/', '<', '>', ':', '"', '|', '?', '*', '\n', '\r':
			return '_'
		default:
			return r
		}
	}, name)
	maxNameLength := 255
	baseName := filepath.Base(replaceName)
	ext := filepath.Ext(baseName)
	extLength := len(ext)
	baseNameWithoutExt := baseName[:len(baseName)-extLength]
	if totalLength := len(baseNameWithoutExt) + extLength; totalLength <= maxNameLength {
		return replaceName
	}

	return strings.TrimSuffix(replaceName, baseName) + baseNameWithoutExt[:maxNameLength-extLength] + ext
}
```

**Comment by sky32** [comment]
error:
  file name too long
fix:
```
	err = i.tpl.Execute(&toName, &fileTemplate{
		DialogID:     from.ID(),
		MessageID:    message.ID,
		MessageDate:  int64(message.Date),
		FileName:     item.Name,
		FileCaption:  message.Message,
		FileSize:     utils.Byte.FormatBinaryBytes(item.Size),
		DownloadDate: time.Now().Unix(),
	})
	if err != nil {
		i.err = errors.Wrap(err, "execute template")
		return false, false
	}
	toName = *bytes.NewBufferString(fixToNameLen(toName.String()))
```
```
func fixToNameLen(name string) string {
	replaceName := strings.Map(func(r rune) rune {
		switch r {
		case ' ', '\\', '/', '<', '>', ':', '"', '|', '?', '*', '\n', '\r':
			return '_'
		default:
			return r
		}
	}, name)
	maxNameLength := 255
	baseName := filepath.Base(replaceName)
	ext := filepath.Ext(baseName)
	extLength := len(ext)
	baseNameWithoutExt := baseName[:len(baseName)-extLength]
	if totalLength := len(baseNameWithoutExt) + extLength; totalLength <= maxNameLength {
		return replaceName
	}

	return strings.TrimSuffix(replaceName, baseName) + baseNameWithoutExt[:maxNameLength-extLength] + ext
}
```

**Pull request merged**
